#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: Merge-upstream
on:
  push:
    paths:
      - '.github/workflows/upstream.yml'
  schedule:
    - cron: 0 */12 * * *
  watch:
    types: started
  repository_dispatch:

jobs:
  merge:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: Ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
        lfs: true

    - name: Set git identity
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Syn upstream
      run: |
        rm -rf `find -maxdepth 1 -type d -name "[!.]*" ! -path "./diy"`
        git rm -r --cache *
        git clone --depth 1 https://github.com/garypang13/luci-app-bypass
        git clone --depth 1 https://github.com/garypang13/luci-app-dnsfilter
        git clone --depth 1 https://github.com/garypang13/openwrt-smartdns && mv -f openwrt-smartdns/* ./ ; rm -Rf openwrt-smartdns
        git clone --depth 1 https://github.com/garypang13/luci-app-eqos

        git clone --depth 1 https://github.com/jerrykuku/luci-app-vssr
        git clone --depth 1 https://github.com/frainzy1477/luci-app-clash
        git clone --depth 1 https://github.com/jefferymvp/luci-app-koolproxyR
        git clone --depth 1 https://github.com/jerrykuku/luci-app-jd-dailybonus
        git clone --depth 1 https://github.com/vernesong/OpenClash && mv -f OpenClash/luci-app-openclash ./ ; rm -Rf OpenClash
        git clone --depth 1 https://github.com/destan19/OpenAppFilter && mv -n OpenAppFilter/* ./ ; rm -Rf OpenAppFilter
        git clone --depth 1 https://github.com/esirplayground/luci-app-poweroff
        git clone --depth 1 https://github.com/fw876/helloworld && mv -n helloworld/* ./ ; rm -Rf helloworld
        git clone --depth 1 https://github.com/linkease/ddnsto-openwrt && mv -n ddnsto-openwrt/* ./ ; rm -Rf ddnsto-openwrt
        
        
        svn co https://github.com/immortalwrt/immortalwrt/trunk/package/ctcgfw/luci-app-adguardhome
        svn co https://github.com/immortalwrt/immortalwrt/trunk/package/ctcgfw/lua-maxminddb
        svn co https://github.com/immortalwrt/immortalwrt/trunk/package/ctcgfw/luci-app-gost
        svn co https://github.com/immortalwrt/immortalwrt/trunk/package/ctcgfw/gost

        
        git clone --depth 1 https://github.com/Lienol/openwrt-package && mv -n openwrt-package/* ./ ; rm -rf openwrt-package
        rm -rf .svn
        echo -e "\q" | svn co https://github.com/immortalwrt/immortalwrt/branches/master/package/lean ./
        rm -rf .svn
        echo -e "\q" | svn co https://github.com/coolsnowwolf/lede/trunk/package/lean ./
        rm -rf .svn
        echo -e "\q" | svn co https://github.com/immortalwrt/immortalwrt/branches/master/package/ctcgfw ./
        rm -rf .svn
        git clone --depth 1 https://github.com/xiaorouji/openwrt-passwall && mv -n openwrt-passwall/* ./ ; rm -Rf openwrt-passwall
        svn export --force https://github.com/immortalwrt/immortalwrt/branches/master/package/ntlf9t && mv -n ntlf9t/* ./ ; rm -rf ntlf9t
        rm -rf .svn
        echo -e "\q" | svn co https://github.com/immortalwrt/immortalwrt/branches/master/package/lienol ./
        rm -rf .svn

    - name: SSH connection to Actions
      uses: garypang13/debugger-action@master
      if: 1 == 0

    - name: Modify
      run: |
        rm -Rf */.git */.svn qt5 openwrt-{chinadns*,simple-obfs,v2ray-plugin,fullconenat,dnsforwarder} cups* subweb \
        mt-drivers coremark npc luci-app-{flowoffload,sfe,appfilter,unblockneteasemusic*,adbyby-plus,advancedsetting,softethervpn,chinadns,docker,samba4} fcgiwrap \
        ddns-scripts_{aliyun,dnspod} UnblockNeteaseMusicGo ipv6-helper adbyby ChinaDNS
        mv mt/drivers mt/mt-drivers
        cp -Rf mt/* ./ && rm -Rf mt
        sed -i "/minisign:minisign/d" luci-app-dnscrypt-proxy2/Makefile
        sed -i 's/shadowsocksr-libev-alt/shadowsocksr-libev-ssr-redir/g' */Makefile
        sed -i 's/shadowsocksr-libev-server/shadowsocksr-libev-ssr-server/g' */Makefile
        sed -i 's/+docker-ce/+docker \\\n\t+dockerd \\\n\t+cgroupfs-mount/' luci-app-dockerman/Makefile
        sed -i 's/+amule/+amule +antileech/' luci-app-amule/Makefile
        rm -f subconverter/patches/010-missing-header.patch
        sed -i 's?../../luci.mk?$(TOPDIR)/feeds/luci/luci.mk?g' */Makefile
        sed -i 's?../../lang?$(TOPDIR)/feeds/packages/lang?g' */Makefile
        bash diy/create_acl_for_luci.sh -a || true
        bash diy/convert_translation.sh -a || true
        rm -Rf antileech/src && git clone https://github.com/persmule/amule-dlp.antiLeech antileech/src
        sed -i '/\/etc\/config\/AdGuardHome/a /etc/config/AdGuardHome.yaml' luci-app-adguardhome/Makefile
        sed -i 's/+rclone\( \|$\)/+rclone +fuse-utils\1/g' luci-app-rclone/Makefile
        sed -i 's/ca-certificates/ca-bundle/g' */Makefile
        sed -i 's/ +kmod-fs-exfat//g' automount/Makefile
        sed -i 's/+libcap /+libcap +libcap-bin /' luci-app-openclash/Makefile
        find */luasrc/view/ -maxdepth 2 -name "*.htm" | xargs -i sed -i 's?"http://" + window.location.hostname?window.location.protocol + "//" + window.location.hostname?g' {}
        getversion() {
        	ver=$(basename $(curl -Ls -o /dev/null -w %{url_effective} https://github.com/$1/releases/latest) | grep -o -E "[0-9].+")
        	[ $ver ] && echo $ver || git ls-remote --tags git://github.com/$1 | cut -d/ -f3- | sort -t. -nk1,2 -k3 | awk '/^[^{]*$/{version=$1}END{print version}' | grep -o -E "[0-9].+"
        }
        sed -i "s/PKG_VERSION:=.*/PKG_VERSION:=$(getversion v2fly/v2ray-core)/g" v2ray/Makefile
        find ./*/ -maxdepth 1 -name "Makefile" ! -path "*tinyfecvpn*" ! -path "*gowebdav*" | xargs -i sed -i "s/PKG_HASH:=.*/PKG_HASH:=skip/g" {}
        sed -i 's/SUBDIRS=/M=/g' */Makefile
        # sed -i 's/\(add ucitrack \(.*\)\)/\1\n\tservice \2 enable/g' luci-app*/root/etc/uci-defaults/*

    - name: Apply patches
      run: find "diy/patches" -type f -name '*.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "cat '%'  | patch -d './' -p1 -E --forward --no-backup-if-mismatch"

    - name: Apply
      run: |
        git add .
        git commit -m "同步更新" || true
        git push
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3
